CREATE DATABASE [tempandhummidity]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tempandhummidity', FILENAME = N'C:\databases2022\tempandhummidity\tempandhummidity.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'tempandhummidity_log', FILENAME = N'C:\databases2022\tempandhummidity\tempandhummidity_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [tempandhummidity] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [tempandhummidity] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [tempandhummidity] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [tempandhummidity] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [tempandhummidity] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [tempandhummidity] SET ARITHABORT OFF 
GO
ALTER DATABASE [tempandhummidity] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [tempandhummidity] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [tempandhummidity] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [tempandhummidity] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [tempandhummidity] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [tempandhummidity] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [tempandhummidity] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [tempandhummidity] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [tempandhummidity] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [tempandhummidity] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [tempandhummidity] SET  DISABLE_BROKER 
GO
ALTER DATABASE [tempandhummidity] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [tempandhummidity] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [tempandhummidity] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [tempandhummidity] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [tempandhummidity] SET  READ_WRITE 
GO
ALTER DATABASE [tempandhummidity] SET RECOVERY FULL 
GO
ALTER DATABASE [tempandhummidity] SET  MULTI_USER 
GO
ALTER DATABASE [tempandhummidity] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [tempandhummidity] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [tempandhummidity] SET DELAYED_DURABILITY = DISABLED 
GO
USE [tempandhummidity]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [tempandhummidity]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [tempandhummidity] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
